### PR TITLE
data/keymaps/i386/neo: use Delete instead of Backspace

### PR DESCRIPTION
**Pull request by vherrmann**
The problem is that the backspace on the 4th layer of neo doesn't work in some (all?) programs. E.g. in emacs, which interprets the backspace action as "C-h". This does not seem to be the case with the delete action. 
Also the backspace key (keycode 14) is bound to the delete action (at least in the keymaps of the neo family). So a switch from the backspace action to the delete action would increase consistency.

### CODE REVIEW

**Comment by legionus** [comment]
I think this PR is wrong. It will break those who are already using the original neo keymap. This can be made as a separate keymap with such changes which will be loaded after the main keymap. Just like a `windowkeys.map`.

By the way, the original project still uses `Backspace` [1].

[1] https://git.neo-layout.org/neo/neo-layout/src/branch/master/linux/console/neo.map#L360

**Comment by vherrmann** [comment]
I have two main points:
1. It won't really break the keymap. The shell functionality will stay the same (AltGr+qwertz-d ≙ Delete the character left to the cursor), and it will increase consistency and functionality. Though it *may* break a broken setup for emacs or other tuis, which assumes AltGr+qwertz-d being the same as C-h…
2. Check your link again :p

**Comment by legionus** [comment]
> I have two main points:
> 
>     1. It won't really break the keymap. The shell functionality will stay the same (AltGr+qwertz-d ≙ Delete the character left to the cursor), and it will increase consistency and functionality. Though it _may_ break a broken setup for emacs or other tuis, which assumes AltGr+qwertz-d being the same as C-h iirc…
> 
>     2. Check your link again :p

Ouch! I think I need more sleep :)
Applied.

**Comment by vherrmann** [comment]
Well, it's not really that you didn't have enough sleep… I just commited the change to the neo repo not until today :>

**Comment by legionus** [comment]
ok. I see :)

**Pull request closed without merging**
