### PR TITLE
data/consolefonts: Add a 16x32 size variant for eurlatgr

### PR DESCRIPTION
**Pull request by jrelvas-ipc**
This PR adds a new version of the `eurlatgr` font with a 32px height.
Characters are simply scaled by x2, with no further changes.
This matches the approach followed by `latarcyrheb-sun`, which shares the same typeface as this font.

This allows the font to be usable in HIDPI displays, such as 4K laptops.

I've also added a symbolic link from `eurlatgr.psfu` to `eurlatgr-16.psfu`, so there's no
breaking changes.

### CODE REVIEW

**Comment by legionus** [comment]
@jrelvas-ipc  kbd uses DCO to format patches. Please add `Signed-off-by` tag in the commit message with real email and name.

https://github.com/legionus/kbd/blob/master/docs/process/howto-contribute.md#sending-patches

**Comment by jrelvas-ipc** [comment]
Apologies. I'll rebase soon.

**Comment by legionus** [comment]
> Characters are simply scaled by x2, with no further changes.

@jrelvas-ipc I have a question. If no changes were made other than scaling x2, then why don't you want to use `setfont -d` ?

**Comment by jrelvas-ipc** [comment]
Oops. I was working with outdated documentation and didn't notice that the `-d` flag existed.

I guess this PR could still make sense if you can't "set" this flag through things like `vconsole.conf`? Probably should be solved there instead though...

**Comment by legionus** [comment]
> Oops. I was working with outdated documentation and didn't notice that the `-d` flag existed.

Supporting two identical fonts that differ only in scale increases support costs.

> I guess this PR could still make sense if you can't "set" this flag through things like `vconsole.conf`? Probably should be solved there instead though...

Yep. Just open an issue in the systemd repo.

**Pull request closed without merging**
