### PR TITLE
Update po/*po files and convert all *po files to UTF-8

### PR DESCRIPTION
**Pull request by kloczek**
After some changes in texts needs to be translated or at least before make new release and call to all translators to update *po files "make -C po update-p" should be executed and  all changes generated by this command should be committed.
This PR pushes all this kind of the changes and convert as well po/{da,id,ro}.po files to UTF-8.

### CODE REVIEW

**Comment by legionus** [comment]
I do this every time before the release. For some time before release all messages are frozen, `kbd.pot` has been updated and sent to translators. After that, I get translations of messages. If you want to change the encoding in the `*.po`, you should contact the project coordinator of translationproject: https://translationproject.org/domain/kbd.html

**Comment by kloczek** [comment]
I think that you do not understand fact that encoding of the .po files it is not something which should be chosen by translators.
When .mo file is generated encoding of the .po files is used on generate this binary file.
At the moment almost everywhere people are using UTF-8 based locale which meas that to display some ISO-8859-* .mo file it needs to be converted on the fly to UTF-8.
In case glibc it needs to be loaded additional translation table. It is possible to avoid such translations if all .po files will be in UTF-8.

**Comment by legionus** [comment]
> I think that you do not understand fact that encoding of the .po files it is not something which should be chosen by translators.

You do not understand that since I take translations from the translationproject.org, then next time I will need to change the encoding again. This makes this PR pointless.

I'll try not to forget about the encoding at the next update of the translations.

**Comment by kloczek** [comment]
And what is the problem with filtering those po files over iconv and/or ask to deliver .po files in UTF?

**Comment by legionus** [comment]
> And what is the problem with filtering those po files over iconv before commit to your repo and/or ask to translators of the .po files in UTF?

This is exactly what I mean when I said that I will try not to forget to do this at the next release.

**Pull request closed without merging**
