### PR TITLE
Rename old and outdated mac-fr to mac-fr-legacy, and create new mac-fr

### PR DESCRIPTION
**Pull request by ToCodeABluejay**
Moved existing 'mac-fr' layout to legacy status as it is outdated and cannot be used on contemporary macs.

Copied 'fr-latin9' as the basis for the new 'mac-fr' layout. Then tweaked the existing layout to fall more in line with the layout shipped on contemporary Macs (mine being a 2020 Macbook Air), as well as some of the finer details of the layout as it exists on mac OS. There may still be a few more tweaks to make in the future, but this is a great start, and can certainly be used without frustration.

Meant to address issue #73 
See here for reference: https://www.apple.com/shop/product/MK2A3FC/A/magic-keyboard-french

Signed-off-by: Gabriel Bauer <gabeb1277@gmail.com>

### CODE REVIEW

**Comment by legionus** [comment]
kbd uses DCO to format patches. Please use your real email and name in commits.

https://github.com/legionus/kbd/blob/master/docs/process/howto-contribute.md#sending-patches

**Comment by ToCodeABluejay** [comment]
Added sign-off...latest commit should be good. Will open another request if I need to make more changes...

**Comment by ToCodeABluejay** [comment]
Let me know if you need anything else!! 🙂

**Comment by legionus** [comment]
I don't see any changes in the commits.

```
$ curl -s https://patch-diff.githubusercontent.com/raw/legionus/kbd/pull/93.patch |grep -Ee '^(Subject|Signed-off-by):'
Subject: [PATCH 1/4] Rename mac-fr.map to mac-fr-legacy.map
Signed-off-by: ToCodeABluejay <73219116+ToCodeABluejay@users.noreply.github.com>
Subject: [PATCH 2/4] Create new mac-fr.map
Signed-off-by: ToCodeABluejay <73219116+ToCodeABluejay@users.noreply.github.com>
Subject: [PATCH 3/4] Update mac-fr.map/fixed encoding
Signed-off-by: ToCodeABluejay <73219116+ToCodeABluejay@users.noreply.github.com>
Subject: [PATCH 4/4] Updated new mac-fr.map yet again...completely untested
```

I also see the garbage that got into the patchset:
```
$ curl -s https://patch-diff.githubusercontent.com/raw/legionus/kbd/pull/93.patch |grep -Ee '^diff --git a/.*/\.DS_Store'
diff --git a/data/.DS_Store b/data/.DS_Store
diff --git a/data/keymaps/.DS_Store b/data/keymaps/.DS_Store
diff --git a/data/keymaps/mac/.DS_Store b/data/keymaps/mac/.DS_Store
```

@ToCodeABluejay I think it's better to make a new PR, where a new keymap will be in the correct encoding, without anything else and all commits will be signed (`git commit -s`).

**Pull request closed without merging**
