### PR TITLE
add timeout param

### PR DESCRIPTION
**Pull request by stzdzyhs**
Hello,  
First thanks  to create this useful tool !
I add a minor change, add a timeout param for showkey, hope it useful.

### CODE REVIEW

**Comment by legionus** [comment]
kbd uses DCO to format patches. Please add `Signed-off-by` tag in the commit message. Everything else looks good.

https://github.com/legionus/kbd/blob/master/docs/process/howto-contribute.md#sending-patches

**Comment by stzdzyhs** [comment]
Signed-off-by added

**Comment by legionus** [comment]
@stzdzyhs What's the point of the second commit?

**Comment by stzdzyhs** [comment]
sorry, I am not familiar with git, do not know how to change the comment of a commit, or delete a commit, 
so, commit the 2nd.
how about this:
I abort this Pull Request, and create a new Pull Request,  I will take careful with the commit comment.

**Comment by legionus** [comment]
> sorry, I am not familiar with git, do not know how to change the comment of a commit, or delete a commit, so, commit the 2nd. how about this: I abort this Pull Request, and create a new Pull Request, I will take careful with the commit comment.

Ok. I will do it by myself.

**Comment by legionus** [comment]
Merged.

**Pull request closed without merging**
